#!/bin/bash

# This script is meant to be run as root on a clean minimal installation of CentOS 7.6.
# If all works properly, it should set up everything to have a working Icinga/IcingaWeb2 installation. 

if [ $(whoami) != "root" ]; then
    echo "This script needs to be run as root."
    exit 0
else
    :
fi

echo "***************************************"
echo "** Beginning Installation of Icinga2 **"
echo "***************************************"

# Change SELinux status. 
SEFILE=/etc/selinux/config
echo "Turning off SELinux"
if [ -f $SEFILE ]; then
    sed -i 's/^SELINUX=[[:alpha:]]\+$/SELINUX=disabled/' $SEFILE #/dev/null 2>&1
    setenforce 0 #/dev/null 2>&1
else
    echo "SELinux file not found. Exiting."
    exit 0
fi

# Add epel-release repository.
echo "Adding epel-release repository." 
yum install -y epel-release #/dev/null 2>&1

# Get Icinga official repo + key.
echo "Adding Icinga official repository."
rpm --import https://packages.icinga.com/icinga.key #/dev/null 2>&1
yum install -y https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm #/dev/null 2>&1

echo "Installing and starting Icinga2. Also installing nagios plugins."
yum install -y icinga2 nagios-plugins-all #/dev/null 2>&1
systemctl enable icinga2 --now #/dev/null 2>&1

echo "Installing and starting mariaDB (mysql). After this script finishes, you should secure the installation with the \"mysql_secure_installation\" command."
yum install -y mariadb-server mariadb #/dev/null 2>&1
systemctl enable mariadb --now #/dev/null 2>&1

echo "Installing IDO modules for mysql."
yum install -y icinga2-ido-mysql #/dev/null 2>&1

echo "Creating database for IDO modules and importing Icinga2 IDO schema into database."

mysql --execute="create database icinga2; grant all privileges on icinga2.* to icinga2@localhost identified by 'icinga123'; flush privileges;" #/dev/null 2>&1

mysql icinga2 < /usr/share/icinga2-ido-mysql/schema/mysql.sql #/dev/null 2>&1

icinga2 feature enable ido-mysql #/dev/null 2>&1
icinga2 feature enable command #/dev/null 2>&1

printf "object IdoMysqlConnection \"ido-mysql\" {\n\tuser = \"icinga2\",\n\tpassword=\"icinga123\",\n\thost=\"localhost\",\n\tdatabase = \"icinga2\"\n}" > /etc/icinga2/features-enabled/ido-mysql.conf

echo "Restarting Icinga2."
systemctl restart icinga2 #/dev/null 2>&1

echo "Configuring firewall."
firewall-cmd --permanent --add-port=5665/tcp --zone=public #/dev/null 2>&1
firewall-cmd --reload #/dev/null 2>&1

echo "FINISHED"
