#!/bin/bash

if [ $(whoami) != "root" ]; then
    echo "This script needs to be run as root."
    exit 0
else
    :
fi

systemctl status snmpd | grep -q "active (running)" && : || yum install -y net-snmp net-snmp-utils > /dev/null 2>&1

echo "view systemview included .1.3.6.1.2.1.25" >> /etc/snmp/snmpd.conf
echo "view systemview included .1.3.6.1.4.1.2021" >> /etc/snmp/snmpd.conf

systemctl enable snmpd --now > /dev/null 2>&1

sudo firewall-cmd --add-service=snmp --zone=public --permanent > /dev/null 2>&1
sudo firewall-cmd --reload > /dev/null 2>&1

snmpget -v 2c -c public localhost laLoad.1 | grep -q "STRING" && echo "SUCCESS" || echo "FAIL"

exit 0
