{
 "title": "Influx All",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES FROM \"ping4\" WITH KEY = \"hostname\""
   }
  ]
 },
 "panels": [
  {
   "title": "Host Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"value\") from hostalive where metric = 'pl' and time > now()-15m AND \"hostname\" =~ /^$hostname$/ group by hostname limit 1;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping4 (Packet Loss)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
     ]
    }
   ]
  },
  {
   "title": "Ping4 (rta)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" }
     ]
    }
   ]
  },
  {
   "title": "CPU % Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "custom_cpu",
     "query": "SELECT (mean(\"value\")  -100) * -1 FROM \"custom_cpu\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'Idle') AND $timeFilter GROUP BY time($__interval), \"metric\", \"hostname\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " -100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Idle" }
     ]
    }
   ]
  },
  {
   "title": "Disk % Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "custom_disk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp_num_procs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "procs" }
     ]
    }
   ]
  },
  {
   "title": "Ram %",
   "type": "graph",
   "description": "Broken rn. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "custom_ram",
     "query": "SELECT mean(\"value\") FROM \"custom_cpu\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'Idle') AND $timeFilter GROUP BY time($__interval), \"metric\", \"hostname\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "RAM above %" }
     ]
    }
   ]
  },
  {
   "title": "Load (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "custom_load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "load1" }
     ]
    }
   ]
  },
  {
   "title": "Load (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "custom_load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "load5" }
     ]
    }
   ]
  },
  {
   "title": "Load (15m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "custom_load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "load15" }
     ]
    }
   ]
  }
 ]
}